var imgTimer;

function imageTimeOut(){
    imgTimer = setTimeout(getRandomPokémon, 0); // this number is the specified delay in milliseconds 
}

function getRandomPokémon() {
    //declare an array to store the images
    var randomPokémon = new Array();

    //insert the URL of images in array
	//randomPokémon[] = "";//
    randomPokémon[0] = "https://user-images.githubusercontent.com/109108536/182645143-93e9546c-1276-4e15-ac74-bd58c25b346d.png";//Bulbasaur
    randomPokémon[1] = "https://user-images.githubusercontent.com/109108536/186333807-15538d93-20d8-4e9c-b2c3-e97d043fbc65.png";//Ivysaur
    randomPokémon[2] = "https://user-images.githubusercontent.com/109108536/188745563-b1f30d38-7052-4b21-9335-cf21f1d070a8.png";//Venusaur
    randomPokémon[3] = "https://user-images.githubusercontent.com/109108536/182645137-6fdfab30-3986-4769-bb17-687fabb8571d.png";//Charmander
    randomPokémon[4] = "https://user-images.githubusercontent.com/109108536/189507323-033fba7d-297e-4fb6-b9e5-872c785282bc.png";//Charmeleon
    randomPokémon[5] = "https://user-images.githubusercontent.com/109108536/190274394-c811d5de-d665-4913-8d0d-bcd57cb8f18f.png";//Charizard
    randomPokémon[6] = "https://user-images.githubusercontent.com/109108536/191074784-42ddb9da-9858-4a26-b27d-d0d0a6faf3d1.png";//Squirtle
    randomPokémon[7] = "https://user-images.githubusercontent.com/109108536/192023134-d9f2d56e-88ee-4af6-bdfa-91ee1d788793.png";//Wartortle
    randomPokémon[8] = "https://user-images.githubusercontent.com/109108536/182371225-7e637597-5591-40f7-9c57-f8cdfefc597e.png";//Pikachu
    randomPokémon[9] = "https://user-images.githubusercontent.com/109108536/185455243-b9cf7aa5-5b17-420b-9494-8720b6676eab.png";//Eevee
    randomPokémon[10] = "https://user-images.githubusercontent.com/109108536/184548331-c87a476c-18bc-452c-b463-589dda31eabe.png";//Vaporeon
    randomPokémon[11] = "https://user-images.githubusercontent.com/109108536/184756655-d8632ee3-ceb1-4aea-89a1-f585c81a255e.png";//Flareon
    randomPokémon[12] = "https://user-images.githubusercontent.com/109108536/183269522-1178a09a-8d59-45b6-90e9-616ddec1098a.png";//Mewtwo
    randomPokémon[13] = "https://user-images.githubusercontent.com/109108536/184548973-d050a180-45d4-433d-ae19-e3a81bcb8bf0.png";//Mew
    
	
	var info = new Array();
	
	//info[0] = "#000 Name";
	info[0] = "#001 Bulbasaur";
	info[1] = "#002 Ivysaur";
	info[2] = "#003 Venusaur";
	info[3] = "#004 Charmander";
    	info[4] = "#005 Charmeleon";
   	info[5] = "#006 Charizard";
   	info[6] = "#007 Squirtle";
   	info[7] = "#028 Wartortle";
	info[8] = "#025 Pikachu";
   	info[9] = "#133 Eevee";
	info[10] = "#134 Vaporeon";
	info[11] = "#136 Flareon";
	info[12] = "#150 Mewtwo";
	info[13] = "#151 Mew";
        
	
	var randomMega = new Array();	//MEGA
	
	randomMega[0] = "https://user-images.githubusercontent.com/109108536/189545695-1a76055d-1aaf-492c-821c-4be0fa2385f3.png";//Mega Venusaur
	
	var infoMega = new Array();
	
	infoMega[0] = "#003 Mega Venusaur";
	
    //repetition option -> for (let i = 0; i < 2; i++) {
        //generate a number and provide to the image to generate randomly
        var number = Math.floor(Math.random() * randomPokémon.length);
        //print the images generated by a random number
        document.getElementById("pokémon").innerHTML += '<img src="' + randomPokémon[number] + '" style="width:38%" />' + info[number];
		
	var number = Math.floor(Math.random() * randomMega.length);
        document.getElementById("mega").innerHTML += '<img src="' + randomMega[number] + '" style="width:38%" />' + infoMega[number];
   //end of "for" }
} //end of function

