var imgTimer;

function imageTimeOut(){
    imgTimer = setTimeout(getRandomPokémon, 0); // this number is the specified delay in milliseconds 
}

function getRandomPokémon() {
    //declare an array to store the images
    var randomPokémon = new Array();

    //insert the URL of images in array
    randomPokémon[0] = "https://user-images.githubusercontent.com/109108536/182645143-93e9546c-1276-4e15-ac74-bd58c25b346d.png";//Bulbasaur
    randomPokémon[1] = "https://user-images.githubusercontent.com/109108536/182645137-6fdfab30-3986-4769-bb17-687fabb8571d.png";//Charmander
    randomPokémon[2] = "https://user-images.githubusercontent.com/109108536/185455243-b9cf7aa5-5b17-420b-9494-8720b6676eab.png";//Eevee
    randomPokémon[3] = "https://user-images.githubusercontent.com/109108536/184756655-d8632ee3-ceb1-4aea-89a1-f585c81a255e.png";//Flareon
   	randomPokémon[4] = "https://user-images.githubusercontent.com/109108536/186333807-15538d93-20d8-4e9c-b2c3-e97d043fbc65.png";//Ivysaur
    randomPokémon[5] = "https://user-images.githubusercontent.com/109108536/184548973-d050a180-45d4-433d-ae19-e3a81bcb8bf0.png";//Mew
    randomPokémon[6] = "https://user-images.githubusercontent.com/109108536/183269522-1178a09a-8d59-45b6-90e9-616ddec1098a.png";//Mewtwo
    randomPokémon[7] = "https://user-images.githubusercontent.com/109108536/182371225-7e637597-5591-40f7-9c57-f8cdfefc597e.png";//Pikachu
    randomPokémon[8] = "https://user-images.githubusercontent.com/109108536/184548331-c87a476c-18bc-452c-b463-589dda31eabe.png";//Vaporeon
    
//randomPokémon[] = "";//
    //repetition option -> for (let i = 0; i < 9; i++) {
        //generate a number and provide to the image to generate randomly
        var number = Math.floor(Math.random() * randomPokémon.length);
        //print the images generated by a random number
        document.getElementById("pokémon").innerHTML += '<img src="' + randomPokémon[number] + '" style="width:80%" />';
   //end of "for" }
} //end of function
